### ISSUE TITLE
Use TT algorithm from Glyphs

### ISSUE THREAD

**Issue by schriftgestalt** [harbortype/ShowTrueTypeCurves#1]
There is a method:
```
path.convertToQuadratic()
```
This is the method used when exporting single TrueType instances.

or for variable fonts:
```
glyph.convertToCompatibleTrueTypeWithError_error_(0.6, None)
```
Both convert in place, so you need to call them on copies of the path and the glyph.

**Comment by harbortype** [comment]
Thanks! I’m already using the first method (for static fonts), but I will implement the variable conversion as an option as well.

**Comment by harbortype** [comment]
@schriftgestalt I have implemented the variable font conversion, so I’m closing this. Once again, thank you for letting me know about it.
